### ISSUE TITLE
请问下，jetbrains里面的请求是否可以代理

### ISSUE THREAD

**Issue by congnews** [lvguanjun/copilot_share#11]

**Comment by lvguanjun** [comment]
你要代理idea里面的什么请求

**Comment by HalfMAI** [comment]
如果idea里的补完请求可以代理的话就更好了，现在jetbrain的配置还是按着之前share-copilot项目中的配置

> {"github.com":{
        "user":"1",
        "oauth_token":"233,
        "dev_override":{
            "copilot_token_url":"http://127.0.0.1:8080/copilot_internal/v2/token"			
        } } }

我看了一下请求Log里其实的确只代理到了token的获取，但是不知道补完能不能也按这种方式

**Comment by lvguanjun** [comment]
![image](https://github.com/lvguanjun/copilot_share/assets/58430934/1367f3e0-c57c-4f0f-8a88-63b6029297c2)
share-copilot 有说过应该是可以实现，我也不会node.js，目前也没用jetbrains家的ide

**Comment by yuliuren** [comment]
想问一下

> ![image](https://private-user-images.githubusercontent.com/58430934/279886655-1367f3e0-c57c-4f0f-8a88-63b6029297c2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDMxNDI5MjgsIm5iZiI6MTcwMzE0MjYyOCwicGF0aCI6Ii81ODQzMDkzNC8yNzk4ODY2NTUtMTM2N2YzZTAtYzU3Yy00ZjBmLThhODgtNjNiNjAyOTI5N2MyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjIxVDA3MTAyOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTAwNmE2ODQ2MmMxYzMzNWQyNjhlYzk5NWY0YjllYmVjODE0ZGE5NmEyNDdkMjA5NWY1MzBhMmVjMTQ2OWY4MzcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ftSKc8nISWh5xKjIAcmsFwvOV4bbm90zmeOrBsBoPF8) [share-copilot](https://gitee.com/chuangxxt/share-copilot/blob/master/readme/codeTipsProxy.md) 有说过应该是可以实现，我也不会node.js，目前也没用jetbrains家的ide

想问一下 share-copilot仓库好像访问受限了 可以右键发一份吗
