### ISSUE TITLE
求助：Chat代理完美运行但Copilot 代理出错

### ISSUE THREAD

**Issue by ZMC12342** [lvguanjun/copilot_share#14]
十分感谢作者的工作，我已成功通过代理服务器运行Github Copilot Chat，但目前有个小问题是GitHub Copilot代理出错，无法通过代理服务器实现代码不全、提示等功能。相关运行日志如下图，GitHub Copilot 的vs code插件版本尝试过V1.127、V1.128、V1.155均不可行，config.py中COMPLETION_URL和COMPLETION_ROUTE均采用默认值，未改动。想请教一下如何解决。

<img width="1080" alt="image" src="https://github.com/lvguanjun/copilot_share/assets/138566877/60e9122b-6158-4f47-bd0c-753c3dfdc82c">

**Comment by lvguanjun** [comment]
completion路由更新了，看一下changelog
这种配置方式在更新上有缺陷。。下个项目改进。

**Comment by lvguanjun** [comment]
https://github.com/lvguanjun/copilot_share/blob/master/CHANGELOG.md

**Comment by lvguanjun** [comment]
看你日志插件怎么请求的老接口，如果你确定没问题的话，你可以将changelog提到的两个配置项更改成插件请求的接口

**Comment by ZMC12342** [comment]
@lvguanjun 请问怎么查询目前最新的插件请求接口呢？不太想用旧的

**Comment by ZMC12342** [comment]
@lvguanjun 还得再请教你一下，我根据Unmatched request: POST URL 修改了相关配置项：
<img width="657" alt="image" src="https://github.com/lvguanjun/copilot_share/assets/138566877/a75e8b7d-26a0-4963-9022-dfcbb6cc32f9">

但这样修改后又出现了新的错误，这应该怎么解决？
<img width="1054" alt="image" src="https://github.com/lvguanjun/copilot_share/assets/138566877/b26d55a3-0daf-4a6b-bb54-4c56fbe5e1f8">

**Comment by ZMC12342** [comment]
> emm 因为我没有实际测试，我只能按照你的日志给出结论，可能是错的，你可以先看一下
> 
> 1. 当前你的插件发的请求在我这里，是copilot之前的老接口
> 2. 这个老接口报错500，我认为是github copilot废弃了这个接口
> 3. 建议升级插件，然后配置文件都更新为新的接口

万分感谢，问题解决了。确实是旧的路由接口被弃用了。我按照你指导的先把代理服务器，更新插件获取新的接口，然后据此修改相关配置项后就没问题了

**Comment by lvguanjun** [comment]
貌似接口又更新为 `/v1/engines/copilot-codex/completions` 了。。。
