### ISSUE TITLE
Github Copilot Chat on Mac 代理失败

### ISSUE THREAD

**Issue by ZMC12342** [lvguanjun/copilot_share#15]
请教一下大家这该如何修复：Copilot 和 Chat 在 vscode on  windows10上均代理成功，但仅Copilot 在vscode on Mac 上正常代理工作，Chat 则是代理失败。两个平台的Github Copilot Chat 插件均使用v0.12.2版本，且客户端的vscode 相关设置相同。
<img width="1147" alt="image" src="https://github.com/lvguanjun/copilot_share/assets/138566877/4d6cffcb-21e9-4eea-a1f5-4c035041f063">

**Comment by lvguanjun** [comment]
可能是插件版本导致的 chat 路由不一致，看下日志能不能看到是请求的什么 api

**Comment by ZMC12342** [comment]
> 可能是插件版本导致的 chat 路由不一致，看下日志能不能看到是请求的什么 api

路由和插件版本都是一致的，请问还有别的可能吗？

**Comment by lvguanjun** [comment]
看下日志，先判断这个 404 是 反代 server 返回的，还是 github 返回的，我猜测应该是反代 server 返回的，可能是配置路由配置错了

**Comment by lvguanjun** [comment]
也不确定...我很久没用这个反代请求了，感觉意义不是很大，起到共享的作用就行了吧

**Comment by lvguanjun** [comment]
![image](https://github.com/lvguanjun/copilot_share/assets/58430934/5515159a-6a09-4bb9-a2e5-abb8689b100a)
我猜测是触发到这个了，说明插件发的请求路由与配置的路由不一致
配置的路由即
![image](https://github.com/lvguanjun/copilot_share/assets/58430934/b9178d66-6997-4bb1-892f-91a26ce6bf55)

**Comment by ZMC12342** [comment]
@lvguanjun 十分感谢，已经解决了。目前在Windows 客户端配置中设置"debug.chatOverrideProxyUrl": "http://127.0.0.1:8080/chat"即可, 但是在Mac里需要补全completions，即"debug.chatOverrideProxyUrl": "http://127.0.0.1:8080/chat/completions"
