### ISSUE TITLE
在v1.128.0版本开始，并没有走代理了。

### ISSUE THREAD

**Issue by wuhao1477** [lvguanjun/copilot_share#3]
问题如题
解决办法：回退v1.127.0
我看作者15小时前更新过脚本，是有解决办法了嘛？

**Comment by lvguanjun** [comment]
直接执行就可以了吧，脚本目前支持 v1.128.0  版本

**Comment by wuhao1477** [comment]
刚刚再次尝试了一下仍是不行，就算是用cocopilot的脚本改了我自己的代理地址也不行。
也确定了 切换回v1.127.0 版本正常使用。
使用两台win11都尝试过了一样的结果

**Comment by lvguanjun** [comment]
你搜一下 copilot 插件目录里面的 extension.js 文件， getTokenUrl 看下附近有没有正确改到

**Comment by lvguanjun** [comment]
![image](https://github.com/lvguanjun/copilot_share/assets/58430934/2b5ba909-c56b-4a44-a0d4-ef9a80281d54)
![image](https://github.com/lvguanjun/copilot_share/assets/58430934/bb9f2c77-8f53-44fa-ae6d-68312bfdeeb1)
预期大概是这样

**Comment by wuhao1477** [comment]
排查完了。目前已经解决。

问题归档：

1. 我的后台用的是share-copilot，在127版本正常使用，但由于正常使用的假象导致误导我认为是你的客户端注入脚本那个后台是匹配的。最后测试的结果是，由于注入的方式不一样以及后台的不一样出现脚本必须要和后台对应才行。最后研究了一下发现，你的这个好像是全代理？share-copilot目前是只代理了一部分请求

2. 在部署本项目在Linux服务器上时遇到的问题：

-  首先python版本必须为3.8以上，原因是用了比较新的py语法

-  在版本比较旧的linux系统上运行时，会出现OpenSSL版本和用到的python库urllib3不兼容，[升级参考](https://blog.csdn.net/yiyihuazi/article/details/116000480)

**Comment by lvguanjun** [comment]
1. 从share-token的代码逻辑看（我就是参考他的代码的^_^），脚本应该是共用的，插件由 v1.127.0 更新到 v1.128.0 版本去除了几个环境变量导致以前的修改方式不再可用，因此本仓库脚本正则匹配到相应位置将“代理服务器路由”和“自定义鉴权”覆盖原始变量，因此后台服务器路由和鉴权正确就可以了，比如 zhile 大佬的 cocopilot
2. 对的，之前是服务器全代理了copilot token & prompt，copilot chat token & prompt，只是客户端可以不配置相关代理，提交 https://github.com/lvguanjun/copilot_share/commit/74d3cf1c14d05c3aa40cc52004d1e92ed1c594bf 可通过配置确定是否开启“提示请求”的代理
3. python 本地版本用的 3.11.4，个人代码追的最新版本

**Comment by lvguanjun** [comment]
> 排查完了。目前已经解决。
> 
> 问题归档：
> 
> 1. 我的后台用的是share-copilot，在127版本正常使用，但由于正常使用的假象导致误导我认为是你的客户端注入脚本那个后台是匹配的。最后测试的结果是，由于注入的方式不一样以及后台的不一样出现脚本必须要和后台对应才行。最后研究了一下发现，你的这个好像是全代理？share-copilot目前是只代理了一部分请求
> 2. 在部署本项目在Linux服务器上时遇到的问题：
> 
> * 首先python版本必须为3.8以上，原因是用了比较新的py语法
> * 在版本比较旧的linux系统上运行时，会出现OpenSSL版本和用到的python库urllib3不兼容，[升级参考](https://blog.csdn.net/yiyihuazi/article/details/116000480)

目前脚本失效可能原因有：
1. 本地存在多个插件目录，脚本会更改低版本插件目录，https://github.com/lvguanjun/copilot_share/commit/cbe50d825dfd8858678aa3eb741974b8f79f18ff 已修复

**Comment by lvguanjun** [comment]
好像目前最新插件校验了是否登录，需要先登录账号（无论是否有copilot权限），才会触发 copilot token 的请求

**Comment by wuhao1477** [comment]
> 希望目前最新插件验证了是否登录，先需要登录账号（无论是否有copilot权限），才会触发copilot token的请求
是的，可以尝试在注入时写如一个假的登录态或者是跳过这个验证了

**Comment by lvguanjun** [comment]
> > 希望目前最新插件验证了是否登录，先需要登录账号（无论是否有copilot权限），才会触发copilot token的请求
> > 是的，可以尝试在注入时写如一个假的登录态或者是跳过这个验证了

js不太会，并且copilot chat 会读取个人信息（比如chat第一句话是跟your name问好），在那一坨加密的js里面关注多个逻辑，感觉蛮麻烦的

**Comment by wuhao1477** [comment]
> > > 希望目前最新插件验证了是否登录，先需要登录账号（无论是否有copilot权限），才会触发copilot token的请求
> > > 是的，可以尝试在注入时写如一个假的登录态或者是跳过这个验证了
> 
> js不太会，并且copilot chat 会读取个人信息（比如chat第一句话是跟your name问好），在那一坨加密的js里面关注多个逻辑，感觉蛮麻烦的


 copilot 插件目录里面的 extension.js 文件中的代码改一下就好了。我正则不是很会，你熟的话可以加到脚本里面去。

- 增加了默认值，让copilot在没登陆态时也能使用代理请求，理论上不影响vscode的手动登录。copilot-chat的话应该是同理的，那个我没用到懒得搞了

 > 原代码【可直接搜索】
 ```javascript
function mM(e){let t=r0e();return P1.authentication.getSession(t,hBe,{silent:!0}).then(r=>r||P1.authentication.getSession(t,t0e,{createIfNone:e}))}
```

>替换成
 ```javascript
function mM(e){let t=r0e();return P1.authentication.getSession(t,hBe,{silent:!0}).then(async r=> r|| await P1.authentication.getSession(t,t0e,{createIfNone:e}) || {"id":"1","account":{"label":"1","id":1},"scopes":["user:email"],"accessToken":"gho_123"} )}
```

**Comment by lvguanjun** [comment]
刚刚写正则去了，没有你改的这么麻烦
