### ISSUE TITLE
关于本项目使用后提出的建议

### ISSUE THREAD

**Issue by wuhao1477** [lvguanjun/copilot_share#4]
### 关于代理请求这块提个愚见

1. 关于封装的代理请求[proxy.py](https://github.com/lvguanjun/copilot_share/blob/master/proxy/proxy.py)中，虽然定义了async函数，但没见到函数中有异步操作。此外，所使用的请求库“requests” 也是同步的，我认为这会导致出现阻塞事件循环，建议可以改用httpx 等异步HTTP客户端库。

2. [在app.py文件中](https://github.com/lvguanjun/copilot_share/blob/cbe50d825dfd8858678aa3eb741974b8f79f18ff/app.py#L77)，使用了await将异步函数转换成了同步导致了chat的结果是一次性返回的，这样写的话很容易在请求中将内容一次性加载到内存中，不利于多用户使用以及持续的数据流传输。其次类似GPT等chat应用基本上都是以流的方式返回，也就是一部分一部分打印出来的效果。

#### 修改建议

-  在请求时使用`StreamingResponse `流的方式返回，在请求时可以有效的减少内存的使用并提供更快的响应时间。

> 本人也对python也不熟。正好在搞一个GPT4的项目，试着用GPT4改了一下不知道对不对哈哈哈哈

```python
// 
import httpx
from starlette.responses import StreamingResponse

async def proxy_request(request: Request, target_url: str) -> StreamingResponse:
    """
    Send a proxy request to the target URL.

    :param request: The request object to proxy.
    :param target_url: The target URL to proxy the request to.
    :return: A streaming response from the target server.
    """
    request_headers = dict(request.headers)
    request_headers.pop("Host", None)
    request_body = await request.body()
    request_method = request.method

    async with httpx.AsyncClient() as client:
        resp = await client.request(
            request_method,
            target_url,
            headers=request_headers,
            data=request_body,
            stream=True
        )

        return StreamingResponse(
            resp.aiter_bytes(),
            headers=resp.headers,
            status_code=resp.status_code
        )
```

**Comment by lvguanjun** [comment]
好的，我也不是太会flask，以前用的tornado，其实本身如果仅token的代理，我感觉是不需要异步的，为了找工作加的异步，然后在反代这块代码用异步疯狂报错，后来放弃了，我应该加个ToDo的，因为我已经忘记了我曾经要排查了hhh  https://github.com/lvguanjun/copilot_share/commit/a357823f8f01a8209e02010d474de298751f899e 这是以前异步报错的提交

**Comment by wuhao1477** [comment]
sse那快如果我们不涉及对数据处理的话，可以直接把接受到的流直接返回回去给客户端就好啦。不需要额外的处理，只要我们keep住连接就好了

**Comment by lvguanjun** [comment]
现在支持copilot chat接到chatgpt，使用gpt4模型来对话，但是还没来得及抽离公共逻辑，先放到demo分支的，可以试试
