### ISSUE TITLE
有没有朋友被嘎了

### ISSUE THREAD

**Issue by tanpengsccd** [lvguanjun/copilot_share#8]
有没有朋友被嘎了. 我是付费用户. 都被GitHub 嘎了
表现为 有账单 但是https://github.com/settings/copilot  页面没有服务.

<img width="1366" alt="image" src="https://github.com/lvguanjun/copilot_share/assets/13959880/1ac1e5fa-1ad3-490b-a3aa-b23f9920b2bf">

**Comment by tanpengsccd** [comment]
账单
<img width="1479" alt="image" src="https://github.com/lvguanjun/copilot_share/assets/13959880/2bbe5b56-fa0b-428d-8a00-b4a94b955cc7">

**Comment by lvguanjun** [comment]
有。学生包成品号也被噶了，不确定是不是copilot to chatgpt 导致的

![image](https://github.com/lvguanjun/copilot_share/assets/58430934/e5489cd7-7ae4-4155-8842-12542128d6c2)

**Comment by lvguanjun** [comment]
> 有没有朋友被嘎了. 我是付费用户. 都被GitHub 嘎了 表现为 有账单 但是https://github.com/settings/copilot 页面没有服务.
> 
> <img alt="image" width="1366" src="https://user-images.githubusercontent.com/13959880/279259077-1ac1e5fa-1ad3-490b-a3aa-b23f9920b2bf.png">

你做了哪些操作，目前用与copilot share的号还完好

**Comment by tanpengsccd** [comment]
> > 有没有朋友被嘎了. 我是付费用户. 都被GitHub 嘎了 表现为 有账单 但是https://github.com/settings/copilot 页面没有服务.
> > <img alt="image" width="1366" src="https://user-images.githubusercontent.com/13959880/279259077-1ac1e5fa-1ad3-490b-a3aa-b23f9920b2bf.png">
> 
> 你做了哪些操作，目前用于copilot share的号还完好

我的初始 token 是 从 jetbrian 里 获取的,但是vscode 用的最多. 其他没有啥特殊的操作.

**Comment by HalfMAI** [comment]
有遇到一样的账号被禁止的情况。

使用方式如下：
1. 免费的试用账号
2. Token来源于jetbrian，格式是为ghu_xxx
3. 只代理Token获取，其它都没代理
4. Jetbrain 和 Vscode混着使用
5. 使用的版本当时没有去掉请求头的IP信息

不太清楚是什么原因，另外使用企业认证的设置现在好像不成功了

**Comment by lvguanjun** [comment]
> 有遇到一样的账号被禁止的情况。
> 
> 使用方式如下：
> 
> 1. 免费的试用账号
> 2. Token来源于jetbrian，格式是为ghu_xxx
> 3. 只代理Token获取，其它都没代理
> 4. Jetbrain 和 Vscode混着使用
> 5. 使用的版本当时没有去掉请求头的IP信息
> 
> 不太清楚是什么原因，另外使用企业认证的设置现在好像不成功了

用的人多吗，目前实测小于等于4人极其稳定（因为用的号商的，我只能确定我分享了3个人），理论上讲同时代理请求更稳定，ip一致嘛

企业认证目前 v1.130.0 版本插件我这边没问题，有报错信息可以截一下

**Comment by tanpengsccd** [comment]
> > 有遇到一样的账号被禁止的情况。
> > 使用方式如下：
> > 
> > 1. 免费的试用账号
> > 2. Token来源于jetbrian，格式是为ghu_xxx
> > 3. 只代理Token获取，其它都没代理
> > 4. Jetbrain 和 Vscode混着使用
> > 5. 使用的版本当时没有去掉请求头的IP信息
> > 
> > 不太清楚是什么原因，另外使用企业认证的设置现在好像不成功了
> 
> 用的人多吗，目前实测小于等于4人极其稳定（因为用的号商的，我只能确定我分享了3个人），理论上讲同时代理请求更稳定，ip一致嘛
> 
> 企业认证目前 v1.130.0 版本插件我这边没问题，有报错信息可以截一下

你第一个 token 是从 vscode 获取的吗?

**Comment by lvguanjun** [comment]
> > > 有遇到一样的账号被禁止的情况。
> > > 使用方式如下：
> > > 
> > > 1. 免费的试用账号
> > > 2. Token来源于jetbrian，格式是为ghu_xxx
> > > 3. 只代理Token获取，其它都没代理
> > > 4. Jetbrain 和 Vscode混着使用
> > > 5. 使用的版本当时没有去掉请求头的IP信息
> > > 
> > > 不太清楚是什么原因，另外使用企业认证的设置现在好像不成功了
> > 
> > 
> > 用的人多吗，目前实测小于等于4人极其稳定（因为用的号商的，我只能确定我分享了3个人），理论上讲同时代理请求更稳定，ip一致嘛
> > 企业认证目前 v1.130.0 版本插件我这边没问题，有报错信息可以截一下
> 
> 你第一个 token 是从 vscode 获取的吗?

从哪儿获取的没什么关系，都是申请一个鉴权而已
参考 https://docs.github.com/en/authentication/keeping-your-account-and-data-secure/about-authentication-to-github#githubs-token-formats

**Comment by tanpengsccd** [comment]
又没交流TG Group?

**Comment by HalfMAI** [comment]
> > 有遇到一样的账号被禁止的情况。
> > 使用方式如下：
> > 
> > 1. 免费的试用账号
> > 2. Token来源于jetbrian，格式是为ghu_xxx
> > 3. 只代理Token获取，其它都没代理
> > 4. Jetbrain 和 Vscode混着使用
> > 5. 使用的版本当时没有去掉请求头的IP信息
> > 
> > 不太清楚是什么原因，另外使用企业认证的设置现在好像不成功了
> 
> 用的人多吗，目前实测小于等于4人极其稳定（因为用的号商的，我只能确定我分享了3个人），理论上讲同时代理请求更稳定，ip一致嘛
> 
> 企业认证目前 v1.130.0 版本插件我这边没问题，有报错信息可以截一下

也就三~五个人，对外是同一IP的
今天更新了Github插件（v1.132.0 ）又可以企业认证了，昨天的话是打开的认证网站是没带IP的

**Comment by lvguanjun** [comment]
> > > 有遇到一样的账号被禁止的情况。
> > > 使用方式如下：
> > > 
> > > 1. 免费的试用账号
> > > 2. Token来源于jetbrian，格式是为ghu_xxx
> > > 3. 只代理Token获取，其它都没代理
> > > 4. Jetbrain 和 Vscode混着使用
> > > 5. 使用的版本当时没有去掉请求头的IP信息
> > > 
> > > 不太清楚是什么原因，另外使用企业认证的设置现在好像不成功了
> > 
> > 
> > 用的人多吗，目前实测小于等于4人极其稳定（因为用的号商的，我只能确定我分享了3个人），理论上讲同时代理请求更稳定，ip一致嘛
> > 企业认证目前 v1.130.0 版本插件我这边没问题，有报错信息可以截一下
> 
> 也就三~五个人，对外是同一IP的 今天更新了Github插件（v1.132.0 ）又可以企业认证了，昨天的话是打开的认证网站是没带IP的

账号禁用应该是账号本身的问题，可能是白嫖使用取消订阅太快自动掉了试用，企业认证应该是使用的问题，你可以查看配置里面（依次是工作区-远程-本地的优先级）是否正确配置了企业认证路由，重载刷新就可以了

**Comment by HalfMAI** [comment]
![image](https://github.com/lvguanjun/copilot_share/assets/5293796/fb171607-488b-4988-a6d8-7313edd65db9)
昨天问了一下他们账号不能使用的原因，说的是检测到滥用。感觉应该是某些额外的接口拿到的信息可以知道github账号不一样之类的吗？因为我有使用jetbrain的，不知道是不是这个原因

**Comment by lvguanjun** [comment]
> ![image](https://user-images.githubusercontent.com/5293796/279881874-fb171607-488b-4988-a6d8-7313edd65db9.png) 昨天问了一下他们账号不能使用的原因，说的是检测到滥用。感觉应该是某些额外的接口拿到的信息可以知道github账号不一样之类的吗？
> 
> 因为我有使用jetbrain的，不知道是不是这个原因。毕竟在jetbrain那边应该是只代理token的请求。
> 
> 另外看了一下真实Token使用的内容中其实有要求Token是希望在1500秒内（获取token 25分钟内）进行刷新的，当前Token刷新是过期前1分钟内（29分钟）才刷新。感觉实际上可以做到15~20分钟内随机刷新可能好一点点（做假就做得真实点点）

好的，等会儿加上随机刷新时间

“因为我有使用jetbrain的，不知道是不是这个原因。毕竟在jetbrain那边应该是只代理token的请求。”
关于这个，个人猜测不是只代理token的原因，因为只要人不够多，就不容易触发风控，（相当于你在3.4处地方正常使用copilot）不过具体是不是jetbrain的行为就不确定了

**Comment by lvguanjun** [comment]
> ![image](https://user-images.githubusercontent.com/5293796/279881874-fb171607-488b-4988-a6d8-7313edd65db9.png) 昨天问了一下他们账号不能使用的原因，说的是检测到滥用。感觉应该是某些额外的接口拿到的信息可以知道github账号不一样之类的吗？
> 
> 因为我有使用jetbrain的，不知道是不是这个原因。毕竟在jetbrain那边应该是只代理token的请求。
> 
> 另外看了一下真实Token使用的内容中其实有要求Token是希望在1500秒内（获取token 25分钟内）进行刷新的，当前Token刷新是过期前1分钟内（29分钟）才刷新。感觉实际上可以做到15~20分钟内随机刷新可能好一点点（做假就做得真实点点）

**真实Token使用的内容中其实有要求Token是希望在1500秒内（获取token 25分钟内）进行刷新的** 这个哪里有说明文档吗，当前实现可能存在问题，因为随机15~20分钟刷新，我们所谓的刷新只是再次请求Github，如果这段时间GitHub认为不必要刷新token，可能会导致所有获取token的请求全部跳过缓存向GitHub请求，因此随机时间要确保能触发GitHub刷新token
